-- Migration: Add AI audit fields to tolovlar table
-- Run this in your Supabase SQL Editor to add AI analysis support

-- 1. Add new columns for AI audit
ALTER TABLE tolovlar 
ADD COLUMN IF NOT EXISTS ai_confidence integer,
ADD COLUMN IF NOT EXISTS ai_extracted_amount integer,
ADD COLUMN IF NOT EXISTS ai_analysis text;

-- 2. Comments explaining the columns
COMMENT ON COLUMN tolovlar.ai_confidence IS 'AI-determined authenticity percentage (0-100)';
COMMENT ON COLUMN tolovlar.ai_extracted_amount IS 'Amount extracted from the receipt by AI (in UZS)';
COMMENT ON COLUMN tolovlar.ai_analysis IS 'Detailed analysis and feedback generated by AI';
