-- Migration history marker.
--
-- This version was applied to production before the canonical repository
-- migration was committed. The reproducible schema change remains in
-- 202609190000_elonlar_system_audience.sql. Supabase compares migration
-- timestamps, so this no-op file keeps local and remote history aligned.
